### ISSUE TITLE
rsync-antora-reference does not apply dry-run setting

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-doc-actions#21]
It seems like `dry-run` is currently ignored. I think [this line](https://github.com/spring-io/spring-doc-actions/blob/6fe7405e565124cef5c447400f7109de7168eba0/rsync-antora-reference/action.yml#L43) might need to be changed to also check `inputs.dry-run`.

**Comment by rwinch** [comment]
This was fixed in 075e9f6fc743937ddeeda24f42833f05e47f6076
